### ISSUE TITLE
NPCs - No movement

### ISSUE THREAD

**Issue by Mysterium** [JadeEmu/JadeCore_547#31]
Hey,

after the mmaps was implemented, the NPC's doesn't move in fight.
![wowscrnshot_100516_210844](https://cloud.githubusercontent.com/assets/4589753/19127602/f19b916a-8b3f-11e6-87e0-03326665cb2d.jpg)

**Comment by Keital** [comment]
cant debug, i dont have mmaps yet, you try reverting some commits related to mmaps in local enviroment and try to figure out wich one broke npc movement

**Comment by Keital** [comment]
Also summoning @alex-kulya i leave this to you!! :D

**Comment by cooler-SAI** [comment]
confirm bug

**Comment by Keital** [comment]
In order to fix this a LOT of work is needed, cause dependencies are incredible long. Also updating the core is a needed step  update recastnavigation, and maybe some other libs. Will remove this from master branch and continue working on my branch, but need some help guys to make this work as a single handed implementation/porting of this feature is a hell of work. cooler make som publicity hahahaha :D

**Comment by cooler-SAI** [comment]
well, we really need more people!! we can invite ANY who can help us!))

**Comment by cooler-SAI** [comment]
I returned mmaps barnch. So people can continue work, when it's will be rady we can merge to master.
